// pokedex-app/svelte-pokedex/src/components/Navigation.svelte
<script>
</script>

<nav className="navigation container">
	<div className="logo">
		<a className="" href="#">
			<img alt="Pokedex App" src="/images/pokedex-logo.png" width="120" />
		</a>
	</div>

	<div className="nav-items">
		<a className="button is-ghost">Home</a>
		<a className="button is-ghost">About</a>
	</div>
</nav>

<style>
</style>

// pokedex-app/nuxt-pokedex/components/Navigation.vue
<template>
  <nav class="navigation container">
    <div class="logo">
      <a class="" href="#">
        <img alt="Pokedex App" :src="require(`~/assets/images/pokedex-logo.png`)" width="120" />
      </a>
    </div>

    <div class="nav-items">
      <a class="button is-ghost">Home</a>
      <a class="button is-ghost">About</a>
    </div>
  </nav>
</template>
