// pokedex-app/next-pokedex/pages/detail/[id].jsx
import Head from 'next/head'
import Link from 'next/link'
import ItemCard from '../../components/ItemCard'

function Detail({ data }) {
  return (
    <>
      <Head>
        <title>Pokedex App - {data.name}</title>
      </Head>
      <Link href="/">
        <a className="button is-ghost mb-4">&lsaquo;&nbsp;Back</a>
      </Link>
      <ItemCard postId={data.id} {...data} />
    </>
  )
}

export async function getServerSideProps(context) {
  const { id } = context.query

  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`)
  const data = await res.json()

  return { props: { data } }
}

export default Detail

// pokedex-app/svelte-pokedex/src/routes/detail/[id]/+page.svelte
<script>
	import { onMount } from 'svelte';

	import ItemCard from '@/components/ItemCard.svelte';

	/** @type {import('./$types').PageData} */
	export let data;
	const { id } = data;
	let res = {};

	onMount(async function () {
		const response = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
		res = await response.json();
	});
</script>

<a href="/" class="button is-ghost mb-4">&lsaquo;&nbsp;Back</a>
<ItemCard postId={id} {...res} />
