// pokedex-app/svelte-pokedex/src/components/Footer.svelte
<div class="container">
	<footer class="footer">
		<div class="content has-text-centered">
			<p>
				<strong>Pokedex Example App</strong> by&nbsp;
				<a href="https://github.com/paulcpk/">Paul Csapak</a>. The source code can be found&nbsp;
				<a href="https://github.com/paulcpk/frontend-framework-comparison"> here </a>
				.
			</p>
		</div>
	</footer>
</div>

// pokedex-app/next-pokedex/components/Footer.jsx
function Footer() {
  return (
    <div className="container">
      <footer className="footer">
        <div className="content has-text-centered">
          <p>
            <strong>Pokedex Example App</strong> by&nbsp;
            <a href="https://github.com/paulcpk/">Paul Csapak</a>. The source
            code can be found&nbsp;
            <a href="https://github.com/paulcpk/frontend-framework-comparison">
              here
            </a>
            .
          </p>
        </div>
      </footer>
    </div>
  )
}

export default Footer
