// pokedex-app/nuxt-pokedex/components/ItemCard.vue
<template>
  <div class="tile">
    <figure class="image">
      <img
        :src="`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${postId}.png`"
        :alt="name"
      />
    </figure>
    <div class="content">
      <h3>
        <span class="prefix">#{{ postId }}:&nbsp;</span>
        {{ name }}
      </h3>
    </div>
    <template v-if="height && weight && types">
      <DetailTable :height="height" :weight="weight" :types="types" />
    </template>
  </div>
</template>

<script>
import DetailTable from './DetailTable.vue'
export default {
  props: ['postId', 'name', 'height', 'weight', 'types'],
  components: { DetailTable },
}
</script>

// pokedex-app/next-pokedex/components/ItemCard.jsx
function DetailTable({ height, weight, types }) {
  return (
    height &&
    weight &&
    types && (
      <table className="mb-4 mt-4">
        <tbody>
          <tr>
            <th>Height:</th>
            <td>{height}</td>
          </tr>
          <tr>
            <th>Weight:</th>
            <td>{weight}</td>
          </tr>
          <tr>
            <th>Types:</th>
            <td>{types.map((type) => type.type.name).join(', ')}</td>
          </tr>
        </tbody>
      </table>
    )
  )
}

function ItemCard({ postId, name, height, weight, types }) {
  return (
    <div className="tile">
      <figure className="image">
        <img
          src={`https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${postId}.png`}
          alt={name}
        />
      </figure>
      <div className="content">
        <h3>
          <span className="prefix">#{postId}:&nbsp;</span>
          {name}
        </h3>
        <DetailTable {...{ height, weight, types }} />
      </div>
    </div>
  )
}

export default ItemCard
